// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Qy4xexkLkAtJuI0pTPE94oUYE0z2f_E',
    appId: '1:312777705485:web:5459252f4cc7dca7abad44',
    messagingSenderId: '312777705485',
    projectId: 'classwork6-3',
    authDomain: 'classwork6-3.firebaseapp.com',
    storageBucket: 'classwork6-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_FbkelsIB_50-0mdBHhpWfG_3TGq9H1Q',
    appId: '1:312777705485:android:266f062cdbc87a0eabad44',
    messagingSenderId: '312777705485',
    projectId: 'classwork6-3',
    storageBucket: 'classwork6-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGCoX5ezkxEF-KyIWa41EkG83i3N5mbEE',
    appId: '1:312777705485:ios:e127dfcef3a89b16abad44',
    messagingSenderId: '312777705485',
    projectId: 'classwork6-3',
    storageBucket: 'classwork6-3.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGCoX5ezkxEF-KyIWa41EkG83i3N5mbEE',
    appId: '1:312777705485:ios:e127dfcef3a89b16abad44',
    messagingSenderId: '312777705485',
    projectId: 'classwork6-3',
    storageBucket: 'classwork6-3.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Qy4xexkLkAtJuI0pTPE94oUYE0z2f_E',
    appId: '1:312777705485:web:116b80b05a85b948abad44',
    messagingSenderId: '312777705485',
    projectId: 'classwork6-3',
    authDomain: 'classwork6-3.firebaseapp.com',
    storageBucket: 'classwork6-3.firebasestorage.app',
  );

}